# Generated by Django 5.2.6 on 2025-10-12 10:55

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Consultant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('contact_number', models.CharField(max_length=15)),
                ('expertise', models.CharField(max_length=100)),
                ('workplace', models.CharField(max_length=100)),
                ('is_verified', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('student_year_level', models.IntegerField()),
                ('student_department', models.CharField(max_length=100)),
                ('student_course', models.CharField(max_length=100)),
                ('student_program', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='consultant',
        ),
        migrations.RemoveField(
            model_name='consultation',
            name='student',
        ),
        migrations.RemoveField(
            model_name='message',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='consultation',
        ),
        migrations.RemoveField(
            model_name='feedback',
            name='student',
        ),
        migrations.RemoveField(
            model_name='message',
            name='sender',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reported_user',
        ),
        migrations.RemoveField(
            model_name='report',
            name='reporter',
        ),
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AlterField(
            model_name='user',
            name='date_joined',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.DeleteModel(
            name='ConsultantProfile',
        ),
        migrations.DeleteModel(
            name='Consultation',
        ),
        migrations.DeleteModel(
            name='Feedback',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
        migrations.DeleteModel(
            name='Report',
        ),
    ]
