# Generated by Django 5.2.6 on 2025-10-22 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0002_admin_consultant_student_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='assigned_consultant',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='ConsultApp.consultant'),
        ),
        migrations.AddField(
            model_name='student',
            name='sessions_completed',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
