# Generated by Django 5.2.6 on 2025-10-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0005_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_year_level',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
