# Generated by Django 5.2.6 on 2025-10-22 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0006_alter_student_student_year_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='student_year_level',
            field=models.IntegerField(default=0),
        ),
    ]
