# Generated by Django 5.2.6 on 2025-10-23 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0007_alter_student_student_year_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
