# Generated by Django 5.2.6 on 2025-10-23 15:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0008_appointment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='consultant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultant_appointments', to='ConsultApp.consultant'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_appointments', to='ConsultApp.student'),
        ),
    ]
