# Generated by Django 5.2.6 on 2025-10-25 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0009_alter_appointment_consultant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expertise', models.CharField(max_length=200)),
                ('profession', models.CharField(max_length=100)),
                ('available_from', models.DateTimeField()),
                ('available_to', models.DateTimeField(blank=True, null=True)),
                ('rate_per_hour', models.PositiveIntegerField(help_text='Rate in PHP per hour')),
                ('meeting_place', models.CharField(help_text='e.g. Online, CIT Campus, Coffee Shop', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Optional: short service description')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='market_listings', to='ConsultApp.consultant')),
            ],
        ),
    ]
