# Generated by Django 5.2.6 on 2025-11-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0010_market'),
    ]

    operations = [
        migrations.AlterField(
            model_name='market',
            name='available_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='market',
            name='available_to',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
