# Generated by Django 5.2.6 on 2025-11-30 08:10

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0011_alter_market_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='research_title',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AddField(
            model_name='market',
            name='available_days',
            field=models.CharField(blank=True, help_text="Comma-separated days (e.g., 'monday,wednesday,friday')", max_length=200),
        ),
        migrations.AlterField(
            model_name='admin',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers, spaces, hyphens, parentheses, and plus signs are allowed.', regex='^[\\d\\s\\-\\(\\)\\+]+$')]),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='topic',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='contact_number',
            field=models.CharField(max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers, spaces, hyphens, parentheses, and plus signs are allowed.', regex='^[\\d\\s\\-\\(\\)\\+]+$')]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='expertise',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='consultant',
            name='workplace',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='market',
            name='expertise',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='market',
            name='meeting_place',
            field=models.CharField(help_text='e.g. Online, CIT Campus, Coffee Shop', max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='market',
            name='profession',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_course',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_department',
            field=models.CharField(max_length=100, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_program',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='verification',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Only numbers, spaces, hyphens, parentheses, and plus signs are allowed.', regex='^[\\d\\s\\-\\(\\)\\+]+$')]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expertise',
            field=models.CharField(max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, and hyphens are allowed.', regex='^[a-zA-Z0-9\\s\\-]+$')]),
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(help_text='Rating from 1 to 5 stars', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.TextField(blank=True, help_text='Optional feedback comment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('appointment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='ConsultApp.appointment')),
                ('consultant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsultApp.consultant')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ConsultApp.student')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
