# Generated by Django 5.2.6 on 2025-11-14 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0011_alter_market_available_from_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='research_title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
