# Generated by Django 5.2.6 on 2025-12-01 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0012_appointment_research_title_market_available_days_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='consultant_marked_as',
            field=models.CharField(blank=True, choices=[('completed', 'Completed'), ('not_completed', 'Not Completed')], help_text="Consultant's assessment of meeting status", max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='disputed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='student_dispute_remark',
            field=models.TextField(blank=True, help_text="Student's explanation if disputing the meeting status", null=True),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('pending_student_review', 'Pending Student Review'), ('disputed', 'Disputed')], default='pending', max_length=30),
        ),
    ]
