# Generated by Django 5.2.6 on 2025-12-04 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0013_appointment_consultant_marked_as_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
