# Generated by Django 5.2.6 on 2025-12-04 13:34

import ConsultApp.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0014_verification_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='verification',
            name='proof_document',
        ),
        migrations.AddField(
            model_name='verification',
            name='license',
            field=models.FileField(blank=True, null=True, storage=ConsultApp.storage_backends.VerificationStorage(), upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='verification',
            name='profile_photo',
            field=models.FileField(blank=True, null=True, storage=ConsultApp.storage_backends.VerificationStorage(), upload_to='verification_docs/'),
        ),
        migrations.AddField(
            model_name='verification',
            name='valid_id',
            field=models.FileField(blank=True, null=True, storage=ConsultApp.storage_backends.VerificationStorage(), upload_to='verification_docs/'),
        ),
    ]
