# Generated by Django 5.2.6 on 2025-12-06 01:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0015_remove_verification_proof_document_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='expertise',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, hyphens, and commas are allowed.', regex='^[a-zA-Z0-9\\s\\-,]+$')]),
        ),
    ]
