# Generated by Django 5.2.6 on 2025-12-07 10:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0016_alter_consultant_expertise'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consultant',
            name='workplace',
            field=models.CharField(max_length=150, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and standard punctuation (-, ., ', &) are allowed.", regex="^[a-zA-Z0-9\\s\\-\\,\\.\\'\\&]+$")]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='expertise',
            field=models.CharField(blank=True, max_length=1000, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, hyphens, and commas are allowed.', regex='^[a-zA-Z0-9\\s\\-,]+$')]),
        ),
        migrations.AlterField(
            model_name='verification',
            name='workplace',
            field=models.CharField(blank=True, max_length=200, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and standard punctuation (-, ., ', &) are allowed.", regex="^[a-zA-Z0-9\\s\\-\\,\\.\\'\\&]+$")]),
        ),
    ]
