# Generated by Django 5.2.6 on 2025-12-07 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0017_alter_consultant_workplace_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='market',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='contact_number',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='expertise',
        ),
        migrations.RemoveField(
            model_name='verification',
            name='workplace',
        ),
    ]
