# Generated by Django 5.2.6 on 2025-12-08 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0018_remove_market_expertise_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled'), ('pending_student_review', 'Pending Student Review'), ('disputed', 'Disputed')], default='pending', max_length=30),
        ),
    ]
