# Generated by Django 5.2.6 on 2025-12-08 10:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ConsultApp', '0019_alter_appointment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='verification',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, validators=[django.core.validators.RegexValidator(message='Only numbers, spaces, hyphens, parentheses, and plus signs are allowed.', regex='^[\\d\\s\\-\\(\\)\\+]+$')]),
        ),
        migrations.AddField(
            model_name='verification',
            name='expertise',
            field=models.CharField(blank=True, max_length=1000, null=True, validators=[django.core.validators.RegexValidator(message='Only letters, numbers, spaces, hyphens, and commas are allowed.', regex='^[a-zA-Z0-9\\s\\-,]+$')]),
        ),
        migrations.AddField(
            model_name='verification',
            name='workplace',
            field=models.CharField(blank=True, max_length=150, null=True, validators=[django.core.validators.RegexValidator(message="Only letters, numbers, spaces, and standard punctuation (-, ., ', &) are allowed.", regex="^[a-zA-Z0-9\\s\\-\\,\\.\\'\\&]+$")]),
        ),
    ]
